{
  "openapi": "3.0.0",
  "info": {
    "title": "Combined API Documentation",
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "http://localhost:8080"
    }
  ],
  "security": [
    {
      "bearerAuth": []
    }
  ],
  "paths": {
    "/admin/createAdmin": {
      "post": {
        "tags": [
          "AccountSetting"
        ],
        "summary": "createAdmin",
        "description": "Endpoint Description for createAdmin\nThis endpoint is used to create a new admin user within the system. Below is a detailed description of each part of the request:\nMethod: POST\nURL: http://localhost:8080/admin/createAdmin\nThe body contains the data required to create the admin user, structured in JSON format:\nemail:\npassword:\nuserName:\nThese parameters are included in the URL and provide additional context for the operation:\nlocationId:\nsessionId:\naccountId:\nType: Bearer Token",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "email": "testingemail89899@gmail.com",
                  "password": "Admin123!",
                  "userName": "John Doe"
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "Client-UUID",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "ClientUUID"
          },
          {
            "name": "locationId",
            "in": "query",
            "schema": {
              "type": "string"
            },
            "example": "locationId"
          },
          {
            "name": "sessionId",
            "in": "query",
            "schema": {
              "type": "string"
            },
            "example": "sessionId"
          },
          {
            "name": "accountId",
            "in": "query",
            "schema": {
              "type": "string"
            },
            "example": "accountId"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "Express"
                }
              },
              "Access-Control-Allow-Origin": {
                "schema": {
                  "type": "string",
                  "example": "*"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Content-Length": {
                "schema": {
                  "type": "integer",
                  "example": "518"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"206-b3OQDEnGC+KJmh5o+pCyAkiEpDg\""
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Fri, 17 Jan 2025 13:11:36 GMT"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "keep-alive"
                }
              },
              "Keep-Alive": {
                "schema": {
                  "type": "string",
                  "example": "timeout=5"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "success": true,
                  "message": "Login successful",
                  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiYjI3MjI4MDEtNjA5NS00YWRkLThlODMtZWQ2NDNjOTBhNGQzIiwicGhvbmVubyI6IisxMzEyMzQ3NTMxMyIsImlhdCI6MTczNzExOTQ5NiwiZXhwIjoxNzM3MjA1ODk2fQ.uc5t6lY3o8049Vr8nD8-FYDqo0djG8rXsa5iIoeRZE4",
                  "user": {
                    "_id": "b2722801-6095-4add-8e83-ed643c90a4d3",
                    "phoneno": "+13123475313",
                    "firstname": "test",
                    "lastname": "user",
                    "email": "testingemai755125@gmail.com",
                    "zipcode": "12345",
                    "dob": "1998-12-31T19:00:00.000Z",
                    "lang": "en"
                  },
                  "accessCode": true
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "headers": {
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "Express"
                }
              },
              "Access-Control-Allow-Origin": {
                "schema": {
                  "type": "string",
                  "example": "*"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Content-Length": {
                "schema": {
                  "type": "integer",
                  "example": "49"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"31-VmptvJVCxgMiCaKMQdd9IkNBIdc\""
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Fri, 17 Jan 2025 13:15:21 GMT"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "keep-alive"
                }
              },
              "Keep-Alive": {
                "schema": {
                  "type": "string",
                  "example": "timeout=5"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "success": false,
                  "message": "Invalid credentials"
                }
              }
            }
          }
        }
      }
    },
    "/admin/createAdmin/latest": {
      "post": {
        "tags": [
          "AccountSetting"
        ],
        "summary": "createAdmin",
        "description": "This is a POST request used to create a new admin user through an API at the endpoint http://localhost:8080/admin/createAdmin/latest.\nThis POST request is designed to create a new admin user. The client sends a request with necessary headers (like the Client-UUID), a body containing admin details (email, password, and username), query parameters for location, session, and account details, and an authentication token for authorization. The response should confirm whether the admin creation was successful or provide an error if there were issues with the request.",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "email": "testingemail89899@gmail.com",
                  "password": "Admin123!",
                  "userName": "John Doe"
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "Client-UUID",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "ClientUUID"
          },
          {
            "name": "locationId",
            "in": "query",
            "schema": {
              "type": "string"
            },
            "example": "locationId"
          },
          {
            "name": "sessionId",
            "in": "query",
            "schema": {
              "type": "string"
            },
            "example": "sessionId"
          },
          {
            "name": "accountId",
            "in": "query",
            "schema": {
              "type": "string"
            },
            "example": "accountId"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "Express"
                }
              },
              "Access-Control-Allow-Origin": {
                "schema": {
                  "type": "string",
                  "example": "*"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Content-Length": {
                "schema": {
                  "type": "integer",
                  "example": "518"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"206-b3OQDEnGC+KJmh5o+pCyAkiEpDg\""
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Fri, 17 Jan 2025 13:11:36 GMT"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "keep-alive"
                }
              },
              "Keep-Alive": {
                "schema": {
                  "type": "string",
                  "example": "timeout=5"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "success": true,
                  "message": "Login successful",
                  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiYjI3MjI4MDEtNjA5NS00YWRkLThlODMtZWQ2NDNjOTBhNGQzIiwicGhvbmVubyI6IisxMzEyMzQ3NTMxMyIsImlhdCI6MTczNzExOTQ5NiwiZXhwIjoxNzM3MjA1ODk2fQ.uc5t6lY3o8049Vr8nD8-FYDqo0djG8rXsa5iIoeRZE4",
                  "user": {
                    "_id": "b2722801-6095-4add-8e83-ed643c90a4d3",
                    "phoneno": "+13123475313",
                    "firstname": "test",
                    "lastname": "user",
                    "email": "testingemai755125@gmail.com",
                    "zipcode": "12345",
                    "dob": "1998-12-31T19:00:00.000Z",
                    "lang": "en"
                  },
                  "accessCode": true
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "headers": {
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "Express"
                }
              },
              "Access-Control-Allow-Origin": {
                "schema": {
                  "type": "string",
                  "example": "*"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Content-Length": {
                "schema": {
                  "type": "integer",
                  "example": "49"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"31-VmptvJVCxgMiCaKMQdd9IkNBIdc\""
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Fri, 17 Jan 2025 13:15:21 GMT"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "keep-alive"
                }
              },
              "Keep-Alive": {
                "schema": {
                  "type": "string",
                  "example": "timeout=5"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "success": false,
                  "message": "Invalid credentials"
                }
              }
            }
          }
        }
      }
    },
    "/admin/createAdmin/newest": {
      "post": {
        "tags": [
          "AccountSetting"
        ],
        "summary": "createAdmin",
        "description": "This is a POST request used to create a new admin user through an API at the endpoint http://localhost:8080/admin/createAdmin/latest.\nThis POST request is designed to create a new admin user. The client sends a request with necessary headers (like the Client-UUID), a body containing admin details (email, password, and username), query parameters for location, session, and account details, and an authentication token for authorization. The response should confirm whether the admin creation was successful or provide an error if there were issues with the request.\nThis is a POST request for creating a new admin user via an API at the endpoint http://localhost:8080/admin/createAdmin/newest. This request is used to add a new administrator to the system.",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "email": "testingemail89899@gmail.com",
                  "password": "Admin123!",
                  "userName": "John Doe"
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "Client-UUID",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "ClientUUID"
          },
          {
            "name": "locationId",
            "in": "query",
            "schema": {
              "type": "string"
            },
            "example": "locationId"
          },
          {
            "name": "sessionId",
            "in": "query",
            "schema": {
              "type": "string"
            },
            "example": "sessionId"
          },
          {
            "name": "accountId",
            "in": "query",
            "schema": {
              "type": "string"
            },
            "example": "accountId"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "Express"
                }
              },
              "Access-Control-Allow-Origin": {
                "schema": {
                  "type": "string",
                  "example": "*"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Content-Length": {
                "schema": {
                  "type": "integer",
                  "example": "518"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"206-b3OQDEnGC+KJmh5o+pCyAkiEpDg\""
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Fri, 17 Jan 2025 13:11:36 GMT"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "keep-alive"
                }
              },
              "Keep-Alive": {
                "schema": {
                  "type": "string",
                  "example": "timeout=5"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "success": true,
                  "message": "Login successful",
                  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiYjI3MjI4MDEtNjA5NS00YWRkLThlODMtZWQ2NDNjOTBhNGQzIiwicGhvbmVubyI6IisxMzEyMzQ3NTMxMyIsImlhdCI6MTczNzExOTQ5NiwiZXhwIjoxNzM3MjA1ODk2fQ.uc5t6lY3o8049Vr8nD8-FYDqo0djG8rXsa5iIoeRZE4",
                  "user": {
                    "_id": "b2722801-6095-4add-8e83-ed643c90a4d3",
                    "phoneno": "+13123475313",
                    "firstname": "test",
                    "lastname": "user",
                    "email": "testingemai755125@gmail.com",
                    "zipcode": "12345",
                    "dob": "1998-12-31T19:00:00.000Z",
                    "lang": "en"
                  },
                  "accessCode": true
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "headers": {
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "Express"
                }
              },
              "Access-Control-Allow-Origin": {
                "schema": {
                  "type": "string",
                  "example": "*"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Content-Length": {
                "schema": {
                  "type": "integer",
                  "example": "49"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"31-VmptvJVCxgMiCaKMQdd9IkNBIdc\""
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Fri, 17 Jan 2025 13:15:21 GMT"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "keep-alive"
                }
              },
              "Keep-Alive": {
                "schema": {
                  "type": "string",
                  "example": "timeout=5"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "success": false,
                  "message": "Invalid credentials"
                }
              }
            }
          }
        }
      }
    },
    "/admin/createAdmin/generation": {
      "post": {
        "tags": [
          "AccountSetting"
        ],
        "summary": "createAdmin",
        "description": "This is a POST request used to create a new admin user through an API at the endpoint http://localhost:8080/admin/createAdmin/latest.\nThis POST request is designed to create a new admin user. The client sends a request with necessary headers (like the Client-UUID), a body containing admin details (email, password, and username), query parameters for location, session, and account details, and an authentication token for authorization. The response should confirm whether the admin creation was successful or provide an error if there were issues with the request.\nThis is a POST request for creating a new admin user via an API at the endpoint http://localhost:8080/admin/createAdmin/newest. This request is used to add a new administrator to the system.\nThis POST request is used to create a new admin user by sending the admin’s details in the body (email, password, and username), including query parameters for location, session, and account information, and using a bearer token for authentication. The client must provide the correct Client-UUID header, as well as a valid BearerToken for authorization. The server will then process the creation of the new admin account. If successful, a confirmation is expected; otherwise, an error will be returned.\nThis POST request is used to create a new admin user in the system via the API endpoint http://localhost:8080/admin/createAdmin/generation. The request sends admin information, including the email, password, and username, and requires certain query parameters and authentication to proceed.",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "email": "testingemail89899@gmail.com",
                  "password": "Admin123!",
                  "userName": "John Doe"
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "Client-UUID",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "ClientUUID"
          },
          {
            "name": "locationId",
            "in": "query",
            "schema": {
              "type": "string"
            },
            "example": "locationId"
          },
          {
            "name": "sessionId",
            "in": "query",
            "schema": {
              "type": "string"
            },
            "example": "sessionId"
          },
          {
            "name": "accountId",
            "in": "query",
            "schema": {
              "type": "string"
            },
            "example": "accountId"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "Express"
                }
              },
              "Access-Control-Allow-Origin": {
                "schema": {
                  "type": "string",
                  "example": "*"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Content-Length": {
                "schema": {
                  "type": "integer",
                  "example": "518"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"206-b3OQDEnGC+KJmh5o+pCyAkiEpDg\""
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Fri, 17 Jan 2025 13:11:36 GMT"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "keep-alive"
                }
              },
              "Keep-Alive": {
                "schema": {
                  "type": "string",
                  "example": "timeout=5"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "success": true,
                  "message": "Login successful",
                  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiYjI3MjI4MDEtNjA5NS00YWRkLThlODMtZWQ2NDNjOTBhNGQzIiwicGhvbmVubyI6IisxMzEyMzQ3NTMxMyIsImlhdCI6MTczNzExOTQ5NiwiZXhwIjoxNzM3MjA1ODk2fQ.uc5t6lY3o8049Vr8nD8-FYDqo0djG8rXsa5iIoeRZE4",
                  "user": {
                    "_id": "b2722801-6095-4add-8e83-ed643c90a4d3",
                    "phoneno": "+13123475313",
                    "firstname": "test",
                    "lastname": "user",
                    "email": "testingemai755125@gmail.com",
                    "zipcode": "12345",
                    "dob": "1998-12-31T19:00:00.000Z",
                    "lang": "en"
                  },
                  "accessCode": true
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "headers": {
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "Express"
                }
              },
              "Access-Control-Allow-Origin": {
                "schema": {
                  "type": "string",
                  "example": "*"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Content-Length": {
                "schema": {
                  "type": "integer",
                  "example": "49"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"31-VmptvJVCxgMiCaKMQdd9IkNBIdc\""
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Fri, 17 Jan 2025 13:15:21 GMT"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "keep-alive"
                }
              },
              "Keep-Alive": {
                "schema": {
                  "type": "string",
                  "example": "timeout=5"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "success": false,
                  "message": "Invalid credentials"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer"
      }
    }
  }
}